[env:seeed_xiao_esp32c3]
platform = espressif32@6.6.0
board = seeed_xiao_esp32c3
framework = arduino
upload_port = COM7
upload_speed = 115200
lib_deps =
    bodmer/TFT_eSPI @ ^2.5
build_flags =
    -include include/tft_setup.h
build_src_filter = +<*> -<display/>
